export const SET_SWAP_TOLERANCE = 'SET_SWAP_TOLERANCE'
export const SET_ADD_LIQUIDITY_TOLERANCE = 'SET_ADD_LIQUIDITY_TOLERANCE'
export const SET_REMOVE_LIQUIDITY_TOLERANCE = 'SET_REMOVE_LIQUIDITY_TOLERANCE'
